### ISSUE TITLE
Dropped States with 'hmmmar' init

### ISSUE THREAD

**Issue by alexmorley** [OHBA-analysis/HMM-MAR#1]
Hey guys,
Not really an issue but just noting that if states are dropped during any of the initialisation cycles then, due to the free energy being lower for the model with more states, the model with fewest states dropped is always selected. Is this ideal behaviour?
Alex

**Comment by vidaurre** [comment]
Hey,
That doesn't necessarily has to be the case. A model with more states can get much better prediction and then have lower free energy, true. But it can also happen that the larger model achieves a similar prediction than the one with less states, and then have higher free energy because of its higher complexity. For example, that'd be the case of a model with two states that are almost identical. The free energy would probably prefer to drop one of the two. The free energy is an ok criterion to decide between these two extremes anyway, and it's the criterion to be optimised within each initialisation, so, if it leads to drop states, dropping shouldn't be that bad?

**Comment by alexmorley** [comment]
Yeah I guess so. I think just intuitively it seems to be like the free-energy is too lenient in that sense. I think you're right. I guess it would be non-trivial to add a param to increase the penalty term?

**Comment by vidaurre** [comment]
All you can do is to play with the hyperparameters of the Bayesian hierarchy, and there is no prior on the number of states to play with I'm afraid, at the moment. You could modify the hyperparameters of other things, but the effect on the number of states is indirect and non-trivial to predict. There is for example the hyperparameters of the transition probability matrix (DirichletDiag option); increasing this will probably affect the final number of states (maybe encouraging to have less) but will have side effects.

**Comment by alexmorley** [comment]
Yep that makes sense. Cheers
