### ISSUE TITLE
Can trial-by-trial features of different states be acquired?

### ISSUE THREAD

**Issue by pauldhami** [OHBA-analysis/HMM-MAR#101]
Hi Dr. Vidaurre,

In the past, I have used your toolbox to model trial-averaged dynamics of networks in the context of participants completing a task (and I have been using this paper as a primary reference: https://www.frontiersin.org/articles/10.3389/fnins.2018.00603/full).

I am now interested in linking features of specific networks that were found to be (on average) modulated by the task to decision making-related parameters on a trial-by-trial basis. My broad goal is to investigate if these networks are in any way related to the decisions made for each trial (as opposed to looking at neurophysiological features of individual regions). 

My question is: can features of networks as described by the HMM be acquired for an individual trial? I believe certain features can be if I remember correctly (for example, task evoked-state occupancy), but am unsure if things like power or coherence can be obtained on a trial by trial basis (or if this should be avoided for any reason).

I also came across one of your more recent papers with the STRM model (https://onlinelibrary.wiley.com/doi/10.1002/hbm.25835), and wonder if that would be more appropriate (or possible) for such a research question. 

Any insight would be greatly appreciated.

Thank you,
Paul

**Comment by vidaurre** [comment]
Hi Paul,

Some things might be tricky to calculate at the trial level, but depends how long is your trial. For example, if you want an estimation of coherence for each state (per trial), then you should at least check that the fractional occupancy of each state and each trial is substantial. If, say, a given state is only present in a given trial during very few time points, then your estimations of coherence/power/etc will be extremely noisy or just invalid.

STRM is the same than TUDA but the other way around (like a GLM instead of a decoder). The problem above would be the same
