### ISSUE TITLE
Understanding the "id_mixture" Parameter in HMM-MAR

### ISSUE THREAD

**Issue by SJFan** [OHBA-analysis/HMM-MAR#108]
Dear HMM-MAR Developers and Community,

Firstly, I would like to express my sincere gratitude for your work on this package. As someone new to this field without a relevant background, it has been an invaluable tool in my research.

I've been exploring the package and I'm curious about the behavior of the "id_mixture" parameter. I would greatly appreciate it if you could provide a bit more explanation on this.

Specifically, when I choose a Gaussian distribution (i.e., option.order == 0), the algorithm appears to segment the data based on instantaneous activation and connectivity, also weighted by transition probabilities.

I'm uncertain about how "id_mixture = false" works in this context. The documentation mentions that the "temporal structure" is ignored. Could you please clarify what this means? Does it imply that the segmentation would not consider the transition probabilities when "id_mixture = false"? This interpretation seems incorrect to me, but I'm struggling to find any other parameters that relate to temporal structure at the moment.

Any insight or guidance you could provide on this would be greatly appreciated. Thank you so much for your time and consideration.

**Comment by vidaurre** [comment]
Hi @SJFan , 

This is to fit a mixture model instead of an HMM. When id_mixture = true, you assume each time point is not dependent on the previous and next time points; i.e. you ignore the data is a time series. 

The HMM will give you a more regularized solution than this, and it's most of the time preferrable. You can use the mixture model as a baseline of comparison. 

Hope that helps.
d
