### ISSUE TITLE
Inputting vpath or Gamma gives different lifetime or FO values.

### ISSUE THREAD

**Issue by AdoNunes** [OHBA-analysis/HMM-MAR#14]
in getStateLifeTimes, getFractionalOccupancy and other gets in utils/analysis the Gamma obtained 
 from the vpath (output from  hmmar) and the Gamma obtained from the Gamma (output from  hmmar) and thresholded at 2/3 do not match. 

Probably in hmmar, to obtain vpath the highest probability per time in gamma was taken instead of thresholding at 2/3.

**Comment by vidaurre** [comment]
Gamma and vpath are different estimations (based on different assumptions) of which state is active at each time point, and therefore they are unlikely to coincide. When using Gamma, it's better a hard threshold than getting the larger probability because otherwise the state time course might become overly unstable. 

I have added a warning recommending the use of vpath
