### ISSUE TITLE
How about the parameter "T" for resting-state fMRI design?

### ISSUE THREAD

**Issue by Chen-Zhiyi** [OHBA-analysis/HMM-MAR#22]
I appreciate contributors for these codes. Nevertheless, I feel weird to set T. Following your guide, it is still unclear to me how to endow the "T". For instance, for the test, I used two participants with 350 time points alongside resting-state fMRI scanning and obtained a matrix for each one by using AAL-116 atlas (350 X 116). Then, I built up one cell to integrate them. However, I have no idea how to build a cell for "T" since no designs or trials are designated here. Any responses would be appreciated.

**Comment by vidaurre** [comment]
Hi Chen-Zhiyi.

T is just to indicate the algorithm when one time series ends and the next one starts. In your case, given that you are specifying one cell per subject, then you should have:

T = cell(2,1); T{1} = 350; T{2} = 350;

because your data for each subject is continuous. 

Hope that helps, let us know if it doesn't.

d
