### ISSUE TITLE
"Matrix is singular" with collinear inputs

### ISSUE THREAD

**Issue by nathanecross** [OHBA-analysis/HMM-MAR#27]
Thanks for providing a well-developed toolbox!

I have had issues getting the hmmmar function to run past initialisation without hitting the following error messages:
_Warning: Matrix is close to singular or badly scaled. Results may be inaccurate.
Warning: Matrix is singular to working precision.​
Warning: State time courses became NaN (out of precision). There are probably extreme events in the data. Using an approximation..​_

My data consists of continuous EEG recordings over a long timespan (~6hours @ 100Hz Fs).
I have removed all artefacts from the data.

I'm using 10 EEG channels, which are all highly correlated (~r=0.9854).
I discovered was able to get it running by setting **options.S** = a 10x10 matrix with 1 down the diagonal and -1 for all off-diagonal elements, which according to the wiki makes the model an ensemble of unrelated AR models.

Does the MAR part of the model have issues running when there is multicollinearity in the data? Is there a better solution than what I tried, and in this case is it best to set the off-diagonal elements to -1, or 0, in **options.S**? 

Sorry if this is an obvious question, I have no background in the MAR theory.

Thanks!
Nathan

**Comment by vidaurre** [comment]
Hi,

The issue is that the MAR is heavily parametrised when there are more than a few channels. This makes the states to fit the data almost perfectly, causing problems during training (technically, this makes the error covariance hard to invert). 

Three possible solutions are
1. Do what you are doing: setting S to make the states ensembles of AR models. This means that you don't model cross-channel interactions
2. Use options.PCA to reduce the data (for example, options.pca=0.8)
3. Use the time-delayed embedded HMM instead of the MAR: https://github.com/OHBA-analysis/HMM-MAR/wiki/User-Guide#embedded 

Many thanks
d
