### ISSUE TITLE
Questions about States and ROIs

### ISSUE THREAD

**Issue by Hongyao-Gao** [OHBA-analysis/HMM-MAR#34]
Dear Prof. Diego Vidaurre,

I have some questions when analyzing data by using the HMM-MAR toolbox.

Firstly, I do not know how to decide the number of states. I learned that there are some indicators, such as free energy, AIC, and so on. I prefer the AIC according to some previous studies, but I failed to calculate the maximum likelihood. I tried to calculate it by the cvhmmmar function, but I found this function is not yet for K(states). Therefore, I was confused about how to decide the number of states.

Secondly, I found that most of the HMM (fMRI)studies applied analysis on the whole brain(14 networks). I'd like to know whether it is fine to define some other specific ROIs(e.g. amygdala, dlPFC…) while analyzing both resting and task data.

I would be very appreciative if you could help me with the question above. 

Thank you very much!
Hongyao Gao

**Comment by vidaurre** [comment]
Hi Hongyao 

I think choosing the number of states with CV could be kind of biased, since you fit the state time courses in the testing set, and therefore the more states you have to choose from the better likelihood you'll get. I guess the most straightforward way would be the free energy, which you get for example as an output parameter of the hmmmar function. In any case the most important thing is that your analyses are robust to a reasonable range of states. So what I would do is to collect solutions from various choices of K, and perform your analyses on each of these.

About the second question, yes. The HMM will run however you define the inputs, so if that makes sense for your question, that's valid. We've seen however that the HMM tends to work better on ICA components than on anatomical parcellations, because of anatomical differences between subjects. It's worth a try anyway. 

Best,
d

**Comment by Hongyao-Gao** [comment]
Thank you for your reply. Your suggestions really help me a lot. And I will take a try as you said.

Best wishes,
Hongyao

**Comment by Hongyao-Gao** [comment]
Thank you for your reply. Your suggestions really help me a lot. And I will take a try as you said.

Best wishes,
Hongyao
