### ISSUE TITLE
How to interpret activity maps vs. connectivity map/circle

### ISSUE THREAD

**Issue by ik362** [OHBA-analysis/HMM-MAR#35]
Dear Dr. Vidaurre,

Thank you very much for sharing this fantastic toolbox.

I just had a question on how to interpret the activity maps and connectvitiy maps/circles.

For reference, I make the figures with:

`for i = [1, 2, ... k]`
    `sprintf(‘Making activity map: %i', i)`
    `makeMap(hmm, i, parc, mask, 0, 0, 0, strcat(‘hmmMapState', num2str(i), ‘MeanActivity'));`
`end`

And for making connectivity circle:

`for i = [1, 2, ... k]`
    `sprintf(‘Making connectivity map: %i', i)`
    `makeConnectivityCircle(hmm, i, roiLabels, 0, 0, 0, thr);`
`end`

Am I right in saying that for state _k_ the mean activity map are the ROIs that “most contribute” to that state whereas the functional connectivity map are the “most connected” regions in that state?

I am asking this as when I plot the connectivity circle I don’t necessarily see the same regions as the activity map.

Thanks,
Isaac

**Comment by vidaurre** [comment]
Hi Isaac, 

I wouldn't say "most contribute". That suggests that the mean is the main thing driving the state changes, but we don't know this without further analyses. 

That is, the mean is "how much" this regions are active when that state is ON, and the connectivity circle is the covariance after we account for the mean, which you can interpret as FC within state (keeping in mind , as I say, that this refers to what is left after taking out the mean). In different words, if you aim at just FC, then maybe you should set the mean to zero (options.zeromean=1). Anyway, I think it's OK to say "that functional connectivity map are the most connected regions in that state."

Normally you would tend to see regions with higher activation (higher mean) having more connectivity to other regions, but as you say that doesn't necessarily need to be the case. 

d

**Comment by ik362** [comment]
Dear @vidaurre ,

Thank you very much for your reply!

My model is currently trained with `options.zeromean=0` (based on neuroimage 2021 fig. SI-2) to investigate the ectivity and connectivity. But I think it might also be interesting to set `options.zeromean=1` as this might be what I am more interested in.

I wanted to ask follow up questiosn on the the `centergraphs` and `scalegraphs` arguments.

1. My interpretation of the `centergraphs` argument is that it allows for interpretation across states; is this correct?
2. And second, `scalegraphs` sets the variance within each state to 1: what is the purpose/when should this be used?

Isaac

**Comment by vidaurre** [comment]
Hi, 

Both parameters are intended to  be used to interrogate relative differences between states: _centergraphs_ just center the plots, so that the average is zero across states, so that's clear. Regarding _scalegraphs_, this is meant to emphasise aspects of the graph where differences across states are not that big, by re-scaling all differences to be equal. For example, if you have a map with visual and prefrontal areas, and there are huge differences across states in visual areas, you wouldn't see much in prefrontal areas. With _scalegraphs_, you would put visual and prefrontal at a similar level by factoring out the dominance of the visual areas. 

Does it make sense? 
d
