### ISSUE TITLE
State lifetime difference between 'getStateOnsets.m', 'getStartFinish_StateVisits.m', and 'getStateLifeTimes.m'

### ISSUE THREAD

**Issue by lsyoath** [OHBA-analysis/HMM-MAR#41]
Hi Diego,
Recently, we were trying to do further analysis based on states generated by HMM, including extracting the onset time, finish time as well as lifetime of each state, to calculate the spatial pattern of them.
I tried scripts named 'getStateOnsets.m', 'getStartFinish_StateVisits.m', and 'getStateLifeTimes.m', then I found that results of the first two scripts were matched, but the TR number of lifetime generated from the third script was different.
Can you answer my confusion about it ?
Thank you very much.

Best,
Siya

**Comment by vidaurre** [comment]
Hi, 

It seems it could be for either of two reasons: 

- That you are using the probabilistic state time courses (the Gamma's) in the getStateLifeTimes function instead of the Viterbi path. 
- The fact that getStateLifeTimes discards may too short visits, depending on the parameter 'threshold'. The other two functions don't do that. 
I've just checked and all produce the same results when feeding a Viterbi path and dispensing with thresholds

d

**Comment by lsyoath** [comment]
Hi Diego,
That's it. I actually used the probabilistic state time courses in the getStateLifeTimes function. I changed to use the Viterbi path, and it works now.
Thank you.
Siya
