### ISSUE TITLE
An issue with how to concatenate the data

### ISSUE THREAD

**Issue by Hongyao-Gao** [OHBA-analysis/HMM-MAR#43]
Dear Prof. Vidaurre,

Thanks for your last reply again, and I have some new questions when analyzing the data deeply. 

I want to explore whether there is a difference in dynamic brain states between two groups (experiment vs. control) on different tasks and task switching. I am really confused about how to concatenate the data. There may be two ways:
1.resting-task1-task2 * N participants;
2.resting * N - task1 * N -task2 * N.
_(N participants include experimental and control groups: N_exp-N_control)_

Furthermore, how should I set the parameter T under this complex condition (I found it could influence the results)? There also may be some different ways:
1.the total amount of time points(just one value);
2. resting-task1-task2 points per participant;
3.N time points per task;
4. 2(group:exp vs. control) _X_ 3(task:resting,task1,task2) conditions,  unique time points per condition.

I am looking forward to your explanations. Thank you!

Kindly regards,
Hongyao

**Comment by vidaurre** [comment]
Hi, 

With respect to the former question, there's no difference. As far as you set T properly to let the algorithm know when each session finishes and the next starts, the order of the subjects/sessions is not taken into account by the HMM inference. If you see differences between HMM runs is not due to the order of the subjects, it's due to the nature of a complex parameter inference, which might find different local minima depending on the initial conditions; see [Vidaurre et al , 2019](https://onlinelibrary.wiley.com/doi/full/10.1002/hbm.24442) for details and solutions about that. 

T should specify the length of every continuous session. For example, the first option would not be correct because there are breaks in the data, and you are not letting the algorithm take these into account. So, for example, if you have subject 1, rest (1000 time points), task 1 (500 time points), task 2 (500 time points); subject 2, the same; subject 3, the same; etc. Then T = [1000;500;500;1000;500;500;1000;500;500;.... ]

Hope that makes sense.
d

**Comment by Hongyao-Gao** [comment]
Thanks for your reply! I believe that I have fully understood the meaning and usage of the parameter T.
