### ISSUE TITLE
Free Energy issue

### ISSUE THREAD

**Issue by ahhcj0716** [OHBA-analysis/HMM-MAR#45]
Hi Dr. Vidaurre,

I got a question about the **Free Energy**.
When I apply the HMM-MAR Gaussian model to my data, the messages showed that in each cycle, the free energy is around -2655428.826, which is a huge negative value.
So I went to check the free energy in the code and found it is comprised of Gamma Entropy, data negative loglikelihood, and other KL values.
The weird thing is that the huge negative value was attributed to the data's negative loglikelihood (element 2).
I remember that the range of the negative loglikelihood is bigger than 0, so it confused me why there appeared a negative value?
Looking forward to your reply.

**Comment by vidaurre** [comment]
Hi,

As you see, the second term is composed of variables dist and NormWishtrace:

avLL = avLL + Gamma(:,k).*(dist - NormWishtrace);
... 
savLL = sum(avLL);

dist should be negative and NormWishtrace should be positive, so that -avLL should be positive. 

In your case, if you set up a breakpoint in line 442 of evalfreeenergy.m, what's the value of sum(dist) and 
sum(NormWishtrace)  ?

Thanks

**Comment by ahhcj0716** [comment]
Hi,
Thanks so much for your reply.
I followed your instruction, and the sum(dist) is negative, and sum(NormWishtrace) is positive.
I found that the avLL changed to positive value after several loops in the following code:
        elseif strcmp(train.covtype,'full')
            ldetWishB = 0.5*logdet(hs.Omega.Gam_rate(regressed,regressed));
            PsiWish_alphasum=0;
            for n = 1:sum(regressed)
                PsiWish_alphasum = PsiWish_alphasum+0.5*psi(hs.Omega.Gam_shape/2+0.5-n/2);
            end
            C = hs.Omega.Gam_shape * hs.Omega.Gam_irate;
            avLL = avLL + Gamma(:,k) * (-ltpi-ldetWishB+PsiWish_alphasum+0.5*sum(regressed)*log(2));
        end 

Thanks again.

**Comment by ahhcj0716** [comment]
And another question is that: If I trained two models from two different datasets, and now there is a new data, is free energy can be used evaluate which model can be better at describing the new data?
Thanks!

**Comment by ahhcj0716** [comment]
If the data length is different, is there any method to normalize the free energy?

**Comment by vidaurre** [comment]
Hello, 
about the original issue, it's hard for me to figure out what happens without being able to properly debug. Could you make a breakpoint there, save the workspace, and send it to me by email (maybe on a dropbox link, if it's too big)? 
About the second point, since it's a separate issue, could you create a new entry?
d

**Comment by ahhcj0716** [comment]
Have re-submitted the question.
And I will send the result to you later this weekend.

Thanks!!!

**Comment by vidaurre** [comment]
Issue continued in https://github.com/OHBA-analysis/HMM-MAR/issues/52
