### ISSUE TITLE
data likelihood issue

### ISSUE THREAD

**Issue by ahhcj0716** [OHBA-analysis/HMM-MAR#52]
Hi,
I am studying the code these days and got some questions about the likelihood estimation.
I see that when using the cvhmmmar to estimate the cross-validation likelihood, there is an arg: cv, that should be set to 1.
So what is this cv for?
If it is set to 0, seems the likelihood results will be changed a lot.

Thanks!

**Comment by vidaurre** [comment]
Hi —thanks for following up on this. 

I guess you mean the cv option of checkoptions.m function? Other than that, there's no parameter called cv. Or you mean something else? 

Regarding your former question, are you still getting  negative  data loglikelihood? You can send me some data and code to replicate this and I will have a look.

d

**Comment by ahhcj0716** [comment]
Hi,
Thanks for your reply.
I mean the function hsinference, the last arg is 'cv'.
And another related question is that, is there any difference between the likelihood estimated by the function hsinference in the function cvhmmmar, and the function evalfreeenergy?

**Comment by vidaurre** [comment]
Hi, 

The parameter cv in hsinference is telling the function whether or not the HMM is run within a cross-validation routine, or just stand-alone. In the latter case, a constant is added to the likelihood to avoid overflow issues. But that would be a problem in a CV loop because it would introduce arbitrary differences between the folds. That parameter is not supposed to be manipulated by users anyway.

There is no difference in terms of the likelihood except for the constant I just mentioned. Of course the evaluation of the free energy has additional terms.
d
