### ISSUE TITLE
Some questions on the function data2struct.m (parameter data.C) 

### ISSUE THREAD

**Issue by zbjbiubiubiu** [OHBA-analysis/HMM-MAR#55]
Hi,
    When I run my program, there were some problems appeared. 
    The first question is. What the function or meaning of the data.C.
    The second question is, why the size of data.C is not the same to its original size, after running the function 'data2struct'. The original code of data2struct.m that we think may cause this problem is attached to this post.

The following code is on line 10-12 of data2struct.m:
if ~isfield(data,'C')
    if options.K>1, 
      data.C = NaN(size(data.X,1)-L*length(T),options.K)

Waiting to receive your kindly reply.

**Comment by vidaurre** [comment]
Hi, 

data.C is used to fix parts of the state time courses to a set value; see this for more information: https://github.com/OHBA-analysis/HMM-MAR/wiki/User-Guide#semi  . The reason it doens't have the same size than the orginal data is because the state time courses can be a bit shorter depending on the model parametrisation (eg if it is a MAR model). 

Could you specify the error you got? 

thanks
d
