### ISSUE TITLE
Riemannian Distance between covariance matrices from HMM-TDE

### ISSUE THREAD

**Issue by mkh1989** [OHBA-analysis/HMM-MAR#73]
I want to check the reproducibility of the states extracted by HMM in different runs. One way is to measure the Riemannian distance between covariance matrices corresponding to states at different runs but I get a complex number (Inf + Infi) as the distance which does not make sense. 
Note: the covariance matrices are not symmetric due to the floating numbers precision. They become symmetric as follow:
covmat = (covmat + covmat') / 2; 
Do you have any suggestions in this regard?

**Comment by vidaurre** [comment]
Hi —thanks. 

It's a bit difficult to diagnose without knowing anything about the covariance matrices themselves. From which options setting you got those? Are you using the built-in code to compute the distance? How did you compute them?  

https://github.com/OHBA-analysis/HMM-MAR/blob/master/utils/math/riemannian_dist.m

d

**Comment by mkh1989** [comment]
Dear Diego,

First of all, thank you for dedicating time to my problem.

I got those covariance matrices in the original space (not in PCs space) using the function getFuncConn. (covmat1 = getFuncConn(hmm1, 1, 1) and covmat2 = getFuncConn(hmm2, 1, 1)). I dont know if it is nedded to give you the options that I used to train HMM-TDE or not.

I used the function you sent its link (riemannian_dist.m)

**Comment by vidaurre** [comment]
Hi, 
I believe the problem is that, when you go to the original space, the matrices (originally computed in PCA space) are by definition not full rank. And a Riemannian distance doesn't like that. Therefore, either you don't use PCA in the HMM inference (maybe not a good idea depending on your data) or compute the Riemannian distances in PCA space. I guess you could make them full rank also by adding some noise.
