### ISSUE TITLE
Question on state topographies

### ISSUE THREAD

**Issue by ateshkoul** [OHBA-analysis/HMM-MAR#82]
Dear Dr. Vidaurre,
I had the following question regarding the usage of HMM-MAR:

State topographies. I am working with 64 channel EEG data and after estimating the HMM (Gaussian model on power time courses), I would like to project back the obtained HMM states into sensor space. From the papers that I read, I wasn't sure how this was performed. Were the state topographies estimated using mvregress (in matlab) that uses the time courses of states (Gamma) as design matrix and the EEG sensor data (or PCs) as response? or was this estimated using a glmfit for each sensor (in such a case, how can we get the spatial maps for each state). Also, would this procedure be similar across other models e.g. Time-Delay Embedded HMM?

Thanks a lot for your help,
Best regards,
Atesh

**Comment by vidaurre** [comment]
Hi Atesh,

I understand that you are running the HMM using a Gaussian distribution with both mean and covariance (because you didn't set options.zeromean=1). In that case, you can get the topography in source space using m = getMean(hmm,k), and then project m back to sensor space by multiplying m by the source-recons weights. 

If that is not possible because you don't have the weights or because you are using a model without the mean (like the TDE), then you can do it manually. Let's say that X is your time series in sensor space, and Gamma is your state time courses (if you are using the TDE, you would have to trim X with a few points off at the beginning and the end of the trial so that number of rows of X and Gamma are the same). Then you can regress Gamma on the data to get contrasts

contrasts = (Gamma' * Gamma + 1e-6 + eye(K)) \ (Gamma' * X);

or alternatively just take the average activation per state k

map_k =  sum(X .* Gamma(:,k)) / sum(Gamma(:,k)) 

Hope that helps
d
