### ISSUE TITLE
The contradiction between Life time and the persistence probability

### ISSUE THREAD

**Issue by Domi0222** [OHBA-analysis/HMM-MAR#86]
Dear Dr. Vidaurre:
Thank you for the beautiful toolbox. 

I recognize that life times and persistence probabilities indicate the states' temporal stability.
However, these are not compatible in some cases.

Sub A's estimated Viterbi path「2, 2, 2, 1, 2, 2, 1, 2, 2, 1, 2, 2, 1, 2, 2」
LT 「3, 2, 2, 2, 2」 = the mean life time is 11/5 = 2.2
TP   state2 to state1 is 4 times, state2 →state2 is 6 times 
Then, the persistence probability is 6/10

Sub B's estimated Viterbi path「2, 2, 2, 2, 2, 2, 1, 2, 1, 2, 1, 2, 1, 1, 1」
LT 「6, 1, 1, 1」 = the mean life time is 9/4 = 2.25 
TP   s2 → s1  4 times, s2 →s2  5 times 
the persistence probability is 5/9 < 6/10

In this case, while LT indicates sub B's state2 was more stable, the persistence probability indicates the other.
How can I decide which subject had a more stable state2?

Could you please provide some suggestions?
Any help would be greatly appreciated.

**Comment by vidaurre** [comment]
Hi,

I followed your comparisons and it seems to be down to your particular definition of stability, rather than a software or an implementation issue. I would say these two metrics are very similar but not equal ,and whereas they will probably agree most of the time, you can find examples when they don't (like here). 

Unfortunately there's not an answer here from first principles, so you have to choose your definition subjectively. 

Sorry not to be of more help
d
