### ISSUE TITLE
Error in hmmdecode

### ISSUE THREAD

**Issue by sophieraible** [OHBA-analysis/HMM-MAR#87]
Hi, I'm trying to run `hmmdecode` (data in cell format input). With the newest version of the toolbox, I encounter the following error:

```
Unrecognized field name "acrosstrial_constrained".

Error in hsinference (line 74)
if ~hmm.train.acrosstrial_constrained

Error in hmmsdecode (line 67)
        [gamma,~,xi] = hsinference(data,Ti,hmm_i,Y,[],XX);

Error in hmmdecode (line 76)
        [Path,Xi] = hmmsdecode(data,T,hmm,type);
```

The problem does not occur when running with an older version of the toolbox downloaded in August 2019. I don't know if I am missing something here or if it's a bug in the newest version. Thank you in advance for your help!

**Comment by vidaurre** [comment]
Hi Sophie,

Thanks for pointing this out. 

That kind of thing happens when we add a new option in the latest version, so HMM  previously trained with an old version  don't have that option. To update the HMM object to the new version of the code, we use the function versCompatibilityFix, which I've just updated to include the option "acrosstrial_constrained". After you pass your HMM through that, hmmdecode should work again. 

I'm closing this here, but please reopen if there's further issues. 

Thanks
d
