### ISSUE TITLE
Questions about HMM on task EEG datasets

### ISSUE THREAD

**Issue by lea231** [OHBA-analysis/HMM-MAR#98]
Hello, Dr. Vidaurre,

I want to drive a Gaussian hmm, and I noticed that your guide said the Gaussian hmm is run on the power time series (options. onpower = 1). I want to ask if the option onpower set to 1 is essential in Gaussian hmm. In my dataset, the state's mean activation appears almost all blue, and the state time series at the group level is messy when I set the onpower option to 1. But if I run on the raw time series (options. Onpower = 0), the results are much better. 

In addition, I want to train two HMMs and then classify the data according to their probability under these two models. When I verify the data, the classification accuracy of one type of data is very low, while the classification accuracy of another type is relatively high. Does this mean that the model failed to identify the two tasks?

Finally, how does the average activation map of states here connect to the brain network? Is it based on the area of activation and experience?

Any thoughts on this would be greatly appreciated.
Best wishes.

Lea

**Comment by vidaurre** [comment]
Hi, 

The Gaussian model on the raw time series does seem strange. Basically you would be having one state for the peak of an oscillation and another for the trough. I would perhaps recommend to use the Time-delay embedded HMM: https://www.nature.com/articles/s41467-018-05316-z

Second question: do you mean you are trying to classify based on the fractional occupancies? This could be sometimes a bit restricted, because it's missing a lot of the information that the HMM contains. The most complete option is the Fisher kernel that we just put together. But it's not fully documented yet (the biorxiv just came out) 

The average activation map of states is just what is in the data. If you are talking about interpretation, I guess that's subjective :) 

d

**Comment by lea231** [comment]
Thank you for your answer but I still have some questions.
When i model the eeg signal on power time series and use the 'getmean' function to get mean activity. I received a 1*no.channels vector. I don't know how to put this vector back to source space. I know the osl provide makemap function but i don't know how to get the parcellation file and the maskfile for eeg. I tried to use a software named sloreta but results seems strange. No matter how large the number of states is set, the activation graph has no negative value. And there will be one or two pairs of states with very little difference in activation area, even if the number of states is only set to three. Do you know how to find the parcellationfile and the mask file, or i need to do something with this state-activated vector? Finally, whether the region of the stereo activation map of the state that is completely free of negativity would be incorrect.

Look forward to your response.
Best wishes.

L
